### ISSUE TITLE
Screen info not updating after profile change.

### ISSUE THREAD

**Issue by X-Olem-X** [dlprows/FocusVolumeControl#3]
Hello again I have found a new bug!
 
When using a second profile that the stream deck auto swaps to based on focused app, it will break the screen part of the plugin,  the plugin screen will just change to 'Focused App Volume' with a gray bar.  It will actually still work, sorta, though there will be no visual feedback until rebooting the stream deck software.

Entirely repeatable bug, happens every single time the profile changes.

**Comment by dlprows** [comment]
Thanks! That's a great catch. I never noticed that because i don't use auto profiles by app.
There was some cleanup code that was causing the problem.

I submitted an update to elgato, or if you want the update before it gets published its [v1.1.2](https://github.com/dlprows/FocusVolumeControl/releases/download/v1.1.2/com.dlprows.focusvolumecontrol.streamDeckPlugin)

**Comment by X-Olem-X** [comment]
Awesome, using the update and works flawlessly again, Thanks!
