### ISSUE TITLE
Suggestions: Ignore windows explorer, don't refresh plugin when changing pages on stream deck, etc

### ISSUE THREAD

**Issue by bananacity** [dlprows/FocusVolumeControl#6]
Now that I got it working I think these couple suggestions would perfect it if they're not too long to implement

1) when going to desktop windows explorer shows up as the focused app with the file explorer icon, also happens when clicking the taskbar. is it possible to just ignore windows explorer as there isn't any volume to control there I believe?

2) app icons are a bit blurry, compared to the elgato volume controller those are a lot crisper so I'm not sure if those are being compressed or if they're grabbing app icons from a different folder with higher res ones?

3) when using firefox the name displayed changes to whatever title the tab i have opened is called. I think if it just remains as "Firefox" that would be better

4) I have the right most dial set to this plugin on all my pages on my stream deck so when i swipe across pages or change folders in my stream deck it flashes as it updates even if i have the same application opened. not sure if it's possible to have all of those share the currently active application from a central place so they don't have to refresh everytime i open a folder or swipe pages?

would be awesome if these aren't too much to implement, maybe you have a donation link to send a couple bucks as I definitely think it's worth it

**Comment by dlprows** [comment]
when you go to windows explorer and it shows as the focused app - the app is looking through the windows volume mixer for apps, and just trying to do some matching of that and the window that has focus

Can you double check that its not showing up in the windows volume mixer?
I'm happy to put in some code in to ignore windows explorer. I just want to make sure there's not something else weird going on.

<hr/>
App icons - i'm not doing any compression to them, i just get the process, and run the windows api to get an icon for the executable at a path. But i can see if there's something i can do to make it better. The most likely scenario i can think of is that the OS is giving me a lower resolution icon than what it could be.

Are the icons you're noticing as more blurry windows store apps, or are they normal programs like chrome/firefox that you installed the normal non-windows store way?

(windows store apps are weird, and get handled a little differently, its part of the pre-release code that i've been experimenting with)


<hr/>
Firefox - yeah, i was afraid that would happen. I've been trying to get the names to show up more similar to how they show in the windows volume mixer, and that involves trying the main window title. I think i know the right way of handling firefox though.


<hr/>
multiple pages/folders
unfortunately, i don't think i can do anything about when you swipe between pages or change folders. I have the same annoyance. The way I understand it, its a limitation of the stream deck software. Each time you add the plugin to the stream deck, it will run it as a separate instance of the executable. So when you change to a different page, it is loading a new executable that has to look through the audio sessions and processes, and all of that work. Its the same stuff that makes it take a split second when changing apps before the screen updates. 

I might be able to do some stuff with saving/loading the current state to a file, because that might be faster to load than the audio sessions. And its simple enough that i can try it. I have limited expectations, but i can see if there's something i can do to make it better.

**Comment by bananacity** [comment]
1) yep just checked and windows explorer isn't in my windows volume mixer

2) I don't have any windows store apps I use so these are all just normal programs like chrome/firefox/gta v etc and yeah it's not terrible quality but it is pretty noticeable when switching to the elgato volume page and comparing the two so would be cool if it managed to be a similar quality

3) cool, not a big deal tbh but probably makes more sense since the titles always get cut off otherwise

4) ah yeah I figured it might be like that, guess we just have to hope elgato come out with a way to set a key or dial to be global to fix that then

but yeah it's a great plugin just figured I would mention those few in case any of them were doable

**Comment by dlprows** [comment]
I have fixes for Firefox title, and the icon being blurry.
Turns out there’s more ways to get the icon and the built in method for c# is the old way

I also have some code that should make having multiple users behave properly, and to make it ignore explorer

I’ll try to get a build uploaded tomorrow. I just ran out of time chasing what appears to be a stream deck bug where telling the display to show something sometimes does nothing

**Comment by dlprows** [comment]
prerelease 1.2.0 has been updated
https://github.com/dlprows/FocusVolumeControl/releases/tag/v1.2.0

It should have fixes for all of these issues

**Comment by bananacity** [comment]
thanks! yep just checked it out and they're all perfect now
